version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  web:
    build: .
    ports:
      - 80:80
    env_file:
      - ./.env
volumes:
  postgres_data:
